- platform: smartir
  name: Air Conditioner
  unique_id: air_con
  device_code: 3300
  controller_data: remote.aaron_s_bedroom_ir_blaster
  temperature_sensor: sensor.aaron_s_bedroom_environment_temperature
  humidity_sensor: sensor.aaron_s_bedroom_environment_humidity
  power_sensor: binary_sensor.air_con_running
