default_config:

automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
browser_mod: !include browser_mod.yaml
calendar: !include calendar.yaml
camera: !include camera.yaml
climate: !include climate.yaml
device_tracker: !include device_tracker.yaml
feedreader: !include feedreader.yaml
frontend: !include frontend.yaml
genius_lyrics: !include genius_lyrics.yaml
group: !include groups.yaml
hdmi_cec: !include hdmi_cec.yaml
homekit: !include homekit.yaml
http: !include http.yaml
influxdb: !include influxdb.yaml
logger: !include logger.yaml
mailgun: !include mailgun.yaml
media_player: !include media_player.yaml
mqtt: !include mqtt.yaml
notify: !include notify.yaml
proxmoxve: !include proxmoxve.yaml
rest_command: !include rest_command.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
simpleicons:
smartir:
spotcast: !include spotcast.yaml
stream: !include stream.yaml
switch: !include switch.yaml
template: !include template.yaml
tts: !include tts.yaml
wake_on_lan:

#disabled:
#  alarm_control_panel: !include alarm_control_panel.yaml
