- platform: universal
  name: Soundbar
  unique_id: soundbar_ump
  device_class: speaker
  attributes:
    source: input_select.soundbar_source
    source_list: "input_select.soundbar_source|options"
    state: binary_sensor.always_on
  commands:
    turn_on:
      service: remote.send_command
      data:
        entity_id: remote.broadlink_remote
        device: soundbar
        command: power_new
    turn_off:
      service: remote.send_command
      data:
        entity_id: remote.broadlink_remote
        device: soundbar
        command: power_new
    volume_up:
      service: remote.send_command
      data:
        entity_id: remote.broadlink_remote
        device: soundbar
        command: vol_up
    volume_down:
      service: remote.send_command
      data:
        entity_id: remote.broadlink_remote
        device: soundbar
        command: vol_down
    volume_mute:
      service: remote.send_command
      data:
        entity_id: remote.broadlink_remote
        device: soundbar
        command: mute
    select_source:
      service: script.soundbar_source
      data:
        source: "{{ source }}"
