- platform: universal
  name: Soundbar
  unique_id: soundbar_ump
  device_class: speaker
  children:
    - binary_sensor.soundbar_mqtt
  attributes:
    source: input_select.soundbar_source
    source_list: "input_select.soundbar_source|options"
  commands:
    turn_on:
      service: remote.send_command
      data:
        entity_id: remote.broadlink_remote
        device: soundbar_ir
        command: power
    turn_off:
      service: remote.send_command
      data:
        entity_id: remote.broadlink_remote
        device: soundbar_ir
        command: power
    volume_up:
      service: remote.send_command
      data:
        entity_id: remote.broadlink_remote
        device: soundbar_ir
        command: vol_up
    volume_down:
      service: remote.send_command
      data:
        entity_id: remote.broadlink_remote
        device: soundbar_ir
        command: vol_down
    volume_mute:
      service: remote.send_command
      data:
        entity_id: remote.broadlink_remote
        device: soundbar_ir
        command: mute
    select_source:
      service: script.soundbar_source
      data:
        source: "{{ source }}"
