- platform: universal
  name: Soundbar
  unique_id: soundbar_ump
  device_class: speaker
  children:
    - binary_sensor.soundbar_mqtt
  # attributes:
  #   - source_list: input_select.soundbar_source|options
  commands:
    turn_on:
      service: remote.send_command
      data:
        entity_id: remote.broadlink_remote
        device: soundbar_ir
        command: power
    turn_off:
      service: remote.send_command
      data:
        entity_id: remote.broadlink_remote
        device: soundbar_ir
        command: power
    volume_up:
      service: remote.send_command
      data:
        entity_id: remote.broadlink_remote
        device: soundbar_ir
        command: vol_up
    volume_down:
      service: remote.send_command
      data:
        entity_id: remote.broadlink_remote
        device: soundbar_ir
        command: vol_down
    volume_mute:
      service: remote.send_command
      data:
        entity_id: remote.broadlink_remote
        device: soundbar_ir
        command: mute
    # select_source:
    #   service: input_select.select_option
    #   data_template:
    #     entity_id: input_select.soundbar_source
    #     option: >-
    #       {% if states('input_select.soundbar_source') == 'Bluetooth' %}
    #       Bluetooth
    #       {% elif states('input_select.soundbar_source') == 'Optical' %}
    #       Optical
    #       {% elif states('input_select.soundbar_source') == 'AUX' %}
    #       AUX
    #       {% endif %}
