binary_sensor:
  - name: "Fire HD Charging"
    state_topic: !secret fully_kiosk_device_info_topic
    device_class: "battery_charging"
    unique_id: "fire_wallpanel_fkb_charging"
    value_template: "{{ value_json['isPlugged'] }}"
    payload_on: true
    payload_off: false
    availability:
      - topic: !secret fully_kiosk_device_info_topic
        value_template: "{{ value_json['mqttConnected'] }}"
        payload_available: true

  - name: "Soundbar MQTT"
    state_topic: "cec/cec/5"
    device_class: "sound"
    unique_id: "soundbar_mqtt_cec"
    payload_on: "on"
    payload_off: "off"

sensor:
  - name: "Electricity - Current Power Usage"
    device_class: power
    expire_after: 3600
    unit_of_measurement: "W"
    value_template: "{{ value_json['electricitymeter']['power']['value'] * 1000 }}"
    unique_id: glow_cad_current_power_usage
    icon: "mdi:flash"
    state_class: measurement
    <<: &glow_cad_elec
      state_topic: !secret glow_cad_local_mqtt_sensor_elec_topic
      json_attributes_topic: !secret glow_cad_local_mqtt_sensor_elec_topic
      json_attributes_template: "{{ value_json['electricitymeter']['energy']['import'] | to_json }}"
      <<: &glow_cad_boilerplate
        availability_topic: !secret glow_cad_local_mqtt_state_topic
        availability_template: "{{ value_json['han']['status'] }}"
        payload_available: "joined"
        payload_not_available: "not joined"
        device:
          name: Glow CAD
          manufacturer: "Hildebrand"
          model: "Glow IHD/CAD SMETS2"
          connections: [["mac", "78:e3:6d:d0:1a:3c"]]

  - name: "Electricity - Cumulative Usage"
    device_class: energy
    unit_of_measurement: "kWh"
    value_template: "{{ value_json['electricitymeter']['energy']['import']['cumulative'] }}"
    unique_id: glow_cad_cumulative_usage
    icon: "mdi:flash"
    state_class: total_increasing
    <<: *glow_cad_elec

  - name: "Electricity - Today's Usage"
    device_class: energy
    unit_of_measurement: "kWh"
    value_template: "{{ value_json['electricitymeter']['energy']['import']['day'] }}"
    unique_id: glow_cad_todays_usage
    icon: "mdi:flash"
    state_class: total_increasing
    <<: *glow_cad_elec

  - name: "Electricity - This Week's Usage"
    device_class: energy
    unit_of_measurement: "kWh"
    value_template: "{{ value_json['electricitymeter']['energy']['import']['week'] }}"
    unique_id: glow_cad_this_weeks_usage
    icon: "mdi:flash"
    state_class: total_increasing
    <<: *glow_cad_elec

  - name: "Electricity - This Month's Usage"
    device_class: energy
    unit_of_measurement: "kWh"
    value_template: "{{ value_json['electricitymeter']['energy']['import']['month'] }}"
    unique_id: glow_cad_this_months_usage
    icon: "mdi:flash"
    state_class: total_increasing
    <<: *glow_cad_elec

  - name: "Gas - Cumulative Volume Usage"
    device_class: gas
    unit_of_measurement: "m³"
    value_template: "{{ value_json['gasmeter']['energy']['import']['cumulativevol'] }}"
    unique_id: glow_cad_gas_cumvol
    icon: "mdi:fire"
    state_class: total_increasing
    <<: &glow_cad_gas
      state_topic: !secret glow_cad_local_mqtt_sensor_gas_topic
      json_attributes_topic: !secret glow_cad_local_mqtt_sensor_gas_topic
      json_attributes_template: "{{ value_json['gasmeter']['energy']['import'] | to_json }}"
      <<: *glow_cad_boilerplate

  - name: "Gas - Cumulative Energy Usage"
    device_class: energy
    unit_of_measurement: "kWh"
    value_template: "{{ value_json['gasmeter']['energy']['import']['cumulative'] }}"
    unique_id: glow_cad_gas_cumeng
    icon: "mdi:fire"
    state_class: total_increasing
    <<: *glow_cad_gas

  - name: "Gas - Today's Usage"
    device_class: energy
    unit_of_measurement: "kWh"
    value_template: "{{ value_json['gasmeter']['energy']['import']['day'] }}"
    unique_id: glow_cad_gas_todays_usage
    icon: "mdi:fire"
    state_class: total_increasing
    <<: *glow_cad_gas

  - name: "Gas - This Week's Usage"
    device_class: energy
    unit_of_measurement: "kWh"
    value_template: "{{ value_json['gasmeter']['energy']['import']['week'] }}"
    unique_id: glow_cad_gas_this_weeks_usage
    icon: "mdi:fire"
    state_class: total_increasing
    <<: *glow_cad_gas

  - name: "Gas - This Month's Usage"
    device_class: energy
    unit_of_measurement: "kWh"
    value_template: "{{ value_json['gasmeter']['energy']['import']['month'] }}"
    unique_id: glow_cad_gas_this_months_usage
    icon: "mdi:fire"
    state_class: total_increasing
    <<: *glow_cad_gas

  ## Hildebrand hosted 👇

  - name: "Home Instant Electricity (Hildebrand)"
    device_class: power
    state_topic: !secret hildebrand_glow_topic
    state_class: measurement
    unit_of_measurement: "W"
    value_template: "{{ value_json['elecMtr']['0702']['04']['00']|int(base=16) }}"
    unique_id: "hildebrand_hosted_mqtt_home_instant_electricity"
    icon: "mdi:flash"

  - name: "Home Electricity (Hildebrand)"
    state_topic: !secret hildebrand_glow_topic
    device_class: energy
    unit_of_measurement: "kWh"
    value_template: "{{ value_json['elecMtr']['0702']['00']['00']|int(base=16) * value_json['elecMtr']['0702']['03']['01']|int(base=16) / value_json['elecMtr']['0702']['03']['02']|int(base=16) }}"
    state_class: total
    unique_id: "hildebrand_hosted_mqtt_home_electricity"
    icon: "mdi:flash"

  - name: "Home Daily Electricity (Hildebrand)"
    state_topic: !secret hildebrand_glow_topic
    device_class: energy
    unit_of_measurement: "kWh"
    value_template: "{{ value_json['elecMtr']['0702']['04']['01']|int(base=16) * value_json['elecMtr']['0702']['03']['01']|int(base=16) / value_json['elecMtr']['0702']['03']['02']|int(base=16) }}"
    state_class: total_increasing
    unique_id: "hildebrand_hosted_mqtt_home_daily_electricity"
    icon: "mdi:flash"

  - name: "Home Weekly Electricity (Hildebrand)"
    state_topic: !secret hildebrand_glow_topic
    device_class: energy
    unit_of_measurement: "kWh"
    value_template: "{{ value_json['elecMtr']['0702']['04']['30']|int(base=16) * value_json['elecMtr']['0702']['03']['01']|int(base=16) / value_json['elecMtr']['0702']['03']['02']|int(base=16) }}"
    state_class: total_increasing
    unique_id: "hildebrand_hosted_mqtt_home_weekly_electricity"
    icon: "mdi:flash"

  - name: "Home Monthly Electricity (Hildebrand)"
    state_topic: !secret hildebrand_glow_topic
    device_class: energy
    unit_of_measurement: "kWh"
    value_template: "{{ value_json['elecMtr']['0702']['04']['40']|int(base=16) * value_json['elecMtr']['0702']['03']['01']|int(base=16) / value_json['elecMtr']['0702']['03']['02']|int(base=16) }}"
    state_class: total_increasing
    unique_id: "hildebrand_hosted_mqtt_home_monthly_electricity"
    icon: "mdi:flash"

  - name: "Home Gas (m3) (Hildebrand)"
    state_topic: !secret hildebrand_glow_topic
    unit_of_measurement: "m³"
    device_class: gas
    value_template: "{{ value_json['gasMtr']['0702']['00']['00']|int(base=16) * value_json['gasMtr']['0702']['03']['01']|int(base=16) / value_json['gasMtr']['0702']['03']['02']|int(base=16) }}"
    state_class: total
    unique_id: "hildebrand_hosted_mqtt_home_gas"
    icon: "mdi:fire"

  - name: "Home Daily Gas (Hildebrand)"
    state_topic: !secret hildebrand_glow_topic
    unit_of_measurement: "kWh"
    device_class: energy
    value_template: "{{ value_json['gasMtr']['0702']['0C']['01']|int(base=16)  * value_json['gasMtr']['0702']['03']['01']|int(base=16) / value_json['gasMtr']['0702']['03']['02']|int(base=16) }}"
    state_class: total_increasing
    unique_id: "hildebrand_hosted_mqtt_home_daily_gas"
    icon: "mdi:fire"

  - name: "Home Weekly Gas (Hildebrand)"
    state_topic: !secret hildebrand_glow_topic
    unit_of_measurement: "kWh"
    device_class: energy
    value_template: "{{ value_json['gasMtr']['0702']['0C']['30']|int(base=16)  * value_json['gasMtr']['0702']['03']['01']|int(base=16) / value_json['gasMtr']['0702']['03']['02']|int(base=16) }}"
    state_class: total_increasing
    unique_id: "hildebrand_hosted_mqtt_home_weekly_gas"
    icon: "mdi:fire"

  - name: "Home Monthly Gas (Hildebrand)"
    state_topic: !secret hildebrand_glow_topic
    unit_of_measurement: "kWh"
    device_class: energy
    value_template: "{{ value_json['gasMtr']['0702']['0C']['40']|int(base=16)  * value_json['gasMtr']['0702']['03']['01']|int(base=16) / value_json['gasMtr']['0702']['03']['02']|int(base=16) }}"
    state_class: total_increasing
    unique_id: "hildebrand_hosted_mqtt_home_monthly_gas"
    icon: "mdi:fire"

  - name: "Fire HD Battery Level"
    state_topic: !secret fully_kiosk_device_info_topic
    device_class: battery
    value_template: "{{ value_json['batteryLevel'] }}"
    unique_id: "fire_wallpanel_fkb_battery_level"
    unit_of_measurement: "%"

  - name: "CAD HAN Status"
    state_topic: !secret glow_cad_local_mqtt_state_topic
    value_template: "{{ value_json['han']['status'] }}"
    unique_id: "glowmarkt_local_mqtt_cad_han_status"
    json_attributes_topic: !secret glow_cad_local_mqtt_state_topic

  - name: SMS2MQTT Signal Strength
    state_topic: sms2mqtt/signal
    value_template: "{{ value_json['SignalStrength'] }}"
    unique_id: sms2mqtt_signal_strength_1
    json_attributes_topic: sms2mqtt/signal
    availability_topic: sms2mqtt/connected
    payload_available: "1"
    payload_not_available: "0"
    state_class: measurement
    unit_of_measurement: dBm

  - name: SMS2MQTT Signal Percentage
    state_topic: sms2mqtt/signal
    value_template: "{{ value_json['SignalPercent'] }}"
    unique_id: sms2mqtt_signal_percent_1
    json_attributes_topic: sms2mqtt/signal
    availability_topic: sms2mqtt/connected
    payload_available: "1"
    payload_not_available: "0"
    state_class: measurement
    unit_of_measurement: "%"

  - name: SMS2MQTT Network Name
    state_topic: sms2mqtt/network
    value_template: "{{ value_json['NetworkName'] }}"
    unique_id: sms2mqtt_network_name_1
    json_attributes_topic: sms2mqtt/network
    availability_topic: sms2mqtt/connected
    payload_available: "1"
    payload_not_available: "0"
    state_class: measurement

  - name: SMS2MQTT Latest Message
    state_topic: sms2mqtt/received
    value_template: "{{ value_json['text'] }}"
    unique_id: sms2mqtt_received_sms_1
    json_attributes_topic: sms2mqtt/received
    availability_topic: sms2mqtt/connected
    payload_available: "1"
    payload_not_available: "0"
    state_class: measurement
