- platform: template
  sensors:
    soundbar_on:
      friendly_name: "Soundbar power status"
      value_template: "{{ states('media_player.hdmi_5') }}"

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
