- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /share
    - type: disk_use
      arg: /share
    - type: disk_free
      arg: /share
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: network_in
      arg: enp1s0
    - type: network_out
      arg: enp1s0

- platform: template
  sensors:
    soundbar_on:
      friendly_name: "Soundbar power status"
      value_template: "{{ states('media_player.hdmi_5') }}"
