- platform: wake_on_lan
  mac: "3c:7c:3f:7d:d0:a6"
  host: 192.168.1.187
  name: "Libby's PC - Sleep/Wake"
  turn_off:
    - service: button.press
      target:
        entity_id: button.libbypc_satellite_sleep

#- platform: tapo
#  host: 192.168.75.206
#  username: !secret gmail_email
#  password: !secret tapo_pass

#- platform: broadlink
#  mac: 24:df:a7:d6:0b:52
#  switches:
#    - name: Soundbar
#      command_on: JgBIAAABJZETNhQRFDYTEhM2FRAUERQRFBIVEBMSFTQUNhMSEzYUNRQ2EzYUERQ2ExITExMRFBEUERQRFDYTEhM2FDUUNhQ1FAANBQ==
#command_off: JgBIAAABJZETNhQRFDYTEhM2FRAUERQRFBIVEBMSFTQUNhMSEzYUNRQ2EzYUERQ2ExITExMRFBEUERQRFDYTEhM2FDUUNhQ1FAANBQ==

#- platform: template
#  switches:
#    soundbar_cec:
#      unique_id: "6e7ea5e0-2dae-4bcc-b4a9-1e6370fb1e57"
#      value_template: "{{ states('sensor.soundbar_on') == 'on' }}"
#      turn_on:
#        service: switch.turn_on
#        data:
#          entity_id: switch.soundbar
#      turn_off:
#        service: switch.turn_off
#        data:
#          entity_id: switch.soundbar